BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "edfdev"
BBFILE_PATTERN_edfdev = "^${LAYERDIR}/"
BBFILE_PRIORITY_edfdev = "10"
LAYERSERIES_COMPAT_edfdev = "scarthgap"
# The hardware/custom recipe layer starts empty until board inputs are added.
BBFILE_PATTERN_IGNORE_EMPTY_edfdev = "1"
