#!/usr/bin/env python3
"""Small EDF wrapper UI for Yocto image settings, not a PetaLinux package catalog."""
import curses
import json
from pathlib import Path
import re
import sys

FIELDS = [('add_packages', 'Add packages', 'IMAGE_INSTALL:append'),
          ('remove_packages', 'Remove direct packages', 'IMAGE_INSTALL:remove'),
          ('add_features', 'Add image features', 'IMAGE_FEATURES:append'),
          ('remove_features', 'Remove image features', 'IMAGE_FEATURES:remove')]
PREFIX = '# edf-menu-settings: '

def load(path):
    if not path.exists():
        return {key: '' for key, _, _ in FIELDS}
    for line in path.read_text().splitlines():
        if line.startswith(PREFIX):
            values = json.loads(line[len(PREFIX):])
            if not isinstance(values, dict) or any(not isinstance(values.get(key), str) for key, _, _ in FIELDS):
                raise ValueError('Invalid saved RootFS settings; file left unchanged.')
            return values
    raise ValueError(f'{path} was not generated by this menu; refusing to overwrite it.')

def save(path, values):
    lines = ['# Generated by ./edf rootfs-menuconfig', PREFIX + json.dumps(values, sort_keys=True)]
    for key, _, variable in FIELDS:
        tokens = values[key].split()
        if any(not re.fullmatch(r'[a-zA-Z0-9][a-zA-Z0-9+_.-]*', token) for token in tokens):
            raise ValueError('Use space-separated package/feature names; no quotes or expressions.')
        lines.append(f'{variable}:pn-edf-linux-disk-image = " {" ".join(tokens)}"')
    pending = path.with_suffix('.tmp')
    pending.write_text('\n'.join(lines)+'\n')
    pending.replace(path)

def menu(screen, path, values):
    selected, message = 0, ''
    if screen.getmaxyx()[0] < 18 or screen.getmaxyx()[1] < 70:
        raise ValueError('Enlarge the terminal to at least 70 columns and 18 rows.')
    curses.curs_set(0)
    screen.keypad(True)
    labels = [label for _, label, _ in FIELDS] + ['Save and exit', 'Cancel']
    while True:
        screen.erase()
        height, width = screen.getmaxyx()
        def put(row, text, attr=0):
            if row < height-1:
                screen.addnstr(row, 0, text, max(1, width-1), attr)
        put(0, 'EDF RootFS configuration (Yocto image settings)', curses.A_BOLD)
        put(2, 'Up/Down: select   Enter: edit   s: save   q/Esc: cancel')
        put(3, 'Names are space-separated. The existing EDF baseline stays in place.')
        put(4, 'Removing a direct package does not remove dependencies of package groups.')
        for number, label in enumerate(labels):
            value = values[FIELDS[number][0]] if number < len(FIELDS) else ''
            put(6+number, f'{label}: {value}', curses.A_REVERSE if selected == number else 0)
        put(13, 'Examples: packages = strace tcpdump; features = tools-debug')
        put(15, message)
        screen.refresh()
        key = screen.getch()
        if key in (ord('q'), 27):
            return False
        if key == curses.KEY_UP:
            selected = (selected-1) % len(labels)
        elif key in (curses.KEY_DOWN, 9):
            selected = (selected+1) % len(labels)
        elif key == ord('s') or (key in (10, 13) and selected == 4):
            try:
                save(path, values)
                return True
            except ValueError as error:
                message = str(error)
        elif key in (10, 13):
            if selected == 5:
                return False
            field, label, _ = FIELDS[selected]
            screen.erase()
            put(0, label + ' (replace the list; empty clears it)', curses.A_BOLD)
            put(2, 'Current: ' + values[field])
            put(4, 'New value: ')
            curses.echo(); curses.curs_set(1)
            try:
                values[field] = screen.getstr(5, 0, 2048).decode('utf-8').strip()
            finally:
                curses.noecho(); curses.curs_set(0)

if __name__ == '__main__':
    try:
        path = Path(sys.argv[1])
        values = load(path)
        if not sys.stdin.isatty() or not sys.stdout.isatty():
            sys.exit('Run rootfs-menuconfig in an interactive terminal.')
        saved = curses.wrapper(menu, path, values)
        print(f'Saved {path}. Rebuild with ./edf linux.' if saved else 'Cancelled; no RootFS settings changed.')
    except KeyboardInterrupt:
        sys.exit("Cancelled; no RootFS settings changed.")
    except (OSError, ValueError, curses.error) as error:
        sys.exit(str(error))
