#!/usr/bin/env python3
"""Persist menuconfig's incremental changes without losing earlier user settings."""
from pathlib import Path
import re
import sys
import os

build = Path(sys.argv[1])
paths = [Path(s.strip()) for s in (build/'kernel-workdir.txt').read_text().splitlines() if s.startswith('/')]
if len(paths) != 1 or not paths[0].is_dir():
    sys.exit('Cannot determine kernel WORKDIR; configuration was not changed.')
fragment = paths[0]/'fragment.cfg'
if not fragment.is_file() or not fragment.read_text().strip():
    print('No new menuconfig changes; existing saved settings retained.')
    sys.exit(0)
folder = build/'conf/edf-kernel'
folder.mkdir(exist_ok=True)
target = folder/'user.cfg'
settings = {}
for text in ([target.read_text()] if target.exists() else []) + [fragment.read_text()]:
    for line in text.splitlines():
        match = re.match(r'(CONFIG_\w+)=|# (CONFIG_\w+) is not set$', line)
        if match:
            settings[match[1] or match[2]] = line
pending = target.with_suffix('.tmp')
pending.write_text('\n'.join(settings.values())+'\n')
pending.replace(target)
conf = build/'conf/edf-kernel.conf'
conf.write_text('''# Generated by ./edf kernel-saveconfig
FILESEXTRAPATHS:prepend:pn-linux-xlnx = "${TOPDIR}/conf/edf-kernel:"
SRC_URI:append:pn-linux-xlnx:@LINUX_MACHINE@ = " file://user.cfg"
'''.replace('@LINUX_MACHINE@', os.environ['LINUX_MACHINE']))
print(f'Saved {target}\nApplied to the selected target kernel on the next ./edf linux build.')
